package com.instagram.creation.a;

import android.util.SparseArray;
import com.facebook.t;
import com.instagram.creation.base.filter.TextureAsset;
import java.util.List;

public enum a
{
  private static final SparseArray<a> X;
  public final int R;
  public final String S;
  public final int T;
  public final String U;
  public final List<TextureAsset> V;
  public final String W;
  
  static
  {
    int i1 = 0;
    Object localObject1 = new b();
    a = 0;
    b = "Normal";
    c = t.filter_normal;
    d = "Normal";
    a = new a("NORMAL", 0, (b)localObject1);
    localObject1 = new b();
    a = 615;
    b = "Lark";
    c = t.filter_lark;
    d = "Lark";
    b = new a("LARK", 1, ((b)localObject1).a("map", "lark/map.png"));
    localObject1 = new b();
    a = 614;
    b = "Reyes";
    c = t.filter_reyes;
    d = "Reyes";
    c = new a("REYES", 2, ((b)localObject1).a("map", "reyes/map.png"));
    localObject1 = new b();
    a = 613;
    b = "Juno";
    c = t.filter_juno;
    d = "Juno";
    d = new a("JUNO", 3, ((b)localObject1).a("map", "juno/map.png"));
    localObject1 = new b();
    a = 612;
    b = "Aden";
    c = t.filter_aden;
    d = "Aden";
    e = new a("ADEN", 4, ((b)localObject1).a("map", "aden/map.png"));
    localObject1 = new b();
    a = 608;
    b = "Perpetua";
    c = t.filter_perpetua;
    d = "Perpetua";
    f = new a("PERPETUA", 5, ((b)localObject1).a("map", "perpetua/map.png").a("overlay_map", "perpetua/overlay_map.png"));
    localObject1 = new b();
    a = 603;
    b = "Ludwig";
    c = t.filter_ludwig;
    d = "Ludwig";
    g = new a("LUDWIG", 6, ((b)localObject1).a("map", "ludwig/map.png"));
    localObject1 = new b();
    a = 605;
    b = "Slumber";
    c = t.filter_slumber;
    d = "Slumber";
    h = new a("SLUMBER", 7, ((b)localObject1).a("map", "slumber/map.png"));
    localObject1 = new b();
    a = 616;
    b = "Crema";
    c = t.filter_crema;
    d = "Crema";
    i = new a("CREMA", 8, ((b)localObject1).a("map", "crema/map.png"));
    localObject1 = new b();
    a = 24;
    b = "Amaro";
    c = t.filter_amaro;
    d = "Amaro";
    j = new a("AMARO", 9, ((b)localObject1).a("map", "amaro/map.png").a("overlay_map", "amaro/overlay_map.png").a("blackboard", "shared/blackboard.png"));
    localObject1 = new b();
    a = 17;
    b = "Mayfair";
    c = t.filter_mayfair;
    d = "Mayfair";
    f = "mayfair/border.png";
    k = new a("MAYFAIR", 10, ((b)localObject1).a("map", "mayfair/colorGradient.png").a("glowField", "mayfair/glowField.png").a("overlay", "mayfair/overlayMap100.png").a("colorOverlay", "mayfair/colorOverlay.png"));
    localObject1 = new b();
    a = 23;
    b = "Rise";
    c = t.filter_rise;
    d = "Rise";
    l = new a("RISE", 11, ((b)localObject1).a("map", "rise/map.png").a("overlay_map", "shared/overlay_map.png").a("blackboard", "shared/blackboard.png"));
    localObject1 = new b();
    a = 26;
    b = "Hudson";
    c = t.filter_hudson;
    d = "Hudson";
    f = "hudson/border.png";
    m = new a("HUDSON", 12, ((b)localObject1).a("map", "hudson/map.png").a("blowout", "hudson/blowout.pkm").a("overlay_map", "shared/overlay_map.png"));
    localObject1 = new b();
    a = 25;
    b = "Valencia";
    c = t.filter_valencia;
    d = "Valencia";
    n = new a("VALENCIA", 13, ((b)localObject1).a("map", "valencia/map.png").a("gradient_map", "valencia/gradient_map.png"));
    localObject1 = new b();
    a = 1;
    b = "X-Pro II";
    c = t.filter_xproii;
    d = "XPro2";
    f = "x_pro2/border.png";
    o = new a("XPRO2", 14, ((b)localObject1).a("map", "x_pro2/map.png").a("vignette_map_plus_darker", "shared/vignette_map_plus_darker.png"));
    localObject1 = new b();
    a = 27;
    b = "Sierra";
    c = t.filter_sierra;
    d = "Sierra";
    f = "sierra/border.png";
    p = new a("SIERRA", 15, ((b)localObject1).a("map", "sierra/map.png").a("smoke", "sierra/smoke.png").a("vignette", "sierra/vignette.png").a("overlay_map", "amaro/overlay_map.png").a("soft_light", "sierra/soft_light.png"));
    localObject1 = new b();
    a = 28;
    b = "Willow";
    c = t.filter_willow;
    d = "Willow";
    q = new a("WILLOW", 16, ((b)localObject1).a("glowMap", "willow/glowField.png").a("overlayMap", "willow/overlayMap81.png").a("borderTexture", "willow/borderTexture.png").a("vignette", "willow/willowVignette.png").a("softLightMap", "willow/willowSoftLight100.png").a("map", "willow/willowMap.png"));
    localObject1 = new b();
    a = 2;
    b = "Lo-Fi";
    c = t.filter_lofi;
    d = "LoFi";
    f = "lo_fi/border.png";
    r = new a("LOFI", 17, ((b)localObject1).a("map", "lo_fi/map.png").a("vignette_map", "lo_fi/vignette_map.png"));
    localObject1 = new b();
    a = 3;
    b = "Earlybird";
    c = t.filter_earlybird;
    d = "Earlybird";
    f = "earlybird/border.png";
    s = new a("EARLYBIRD", 18, ((b)localObject1).a("map", "earlybird/earlybird_map.png").a("curves_map", "earlybird/curves_map.png").a("vignette_map_plus_darker", "shared/vignette_map_plus_darker.png").a("overlay_map", "earlybird/overlay_map.png").a("blowout_map", "earlybird/blowout_map.png"));
    localObject1 = new b();
    a = 22;
    b = "Brannan";
    c = t.filter_brannan;
    d = "Brannan";
    f = "brannan/border.png";
    t = new a("BRANNAN", 19, ((b)localObject1).a("map", "brannan/map.png").a("luma_map", "brannan/luma_map.png").a("screen_map", "brannan/screen_map.png").a("blowout_map", "brannan/blowout_map.png").a("contrast_map", "brannan/contrast_map.png"));
    localObject1 = new b();
    a = 10;
    b = "Inkwell";
    c = t.filter_inkwell;
    d = "Inkwell";
    f = "shared/border_white.png";
    u = new a("INKWELL", 20, ((b)localObject1).a("map", "inkwell/map.png"));
    localObject1 = new b();
    a = 21;
    b = "Hefe";
    c = t.filter_hefe;
    d = "Hefe";
    f = "shared/border_black.png";
    v = new a("HEFE", 21, ((b)localObject1).a("map", "hefe/map.png").a("metal", "hefe/metal.pkm").a("edge_burn", "shared/edge_burn.pkm").a("gradient_map", "hefe/gradient_map.png").a("soft_light_map", "hefe/soft_light_map.png"));
    localObject1 = new b();
    a = 15;
    b = "Nashville";
    c = t.filter_nashville;
    d = "Nashville";
    f = "nashville/border.png";
    w = new a("NASHVILLE", 22, ((b)localObject1).a("map", "nashville/map.png"));
    localObject1 = new b();
    a = 18;
    b = "Sutro";
    c = t.filter_sutro;
    d = "Sutro";
    f = "shared/border_black.png";
    x = new a("SUTRO", 23, ((b)localObject1).a("map", "sutro/map.png").a("metal", "sutro/metal.pkm").a("edge_burn", "sutro/edge_burn.pkm").a("black_overlay_map", "shared/black_overlay_map.png").a("soft_light_map", "shared/soft_light_map.png"));
    localObject1 = new b();
    a = 19;
    b = "Toaster";
    c = t.filter_toaster;
    d = "Toaster";
    f = "shared/border_white.png";
    y = new a("TOASTER", 24, ((b)localObject1).a("map", "toaster/map.png").a("metal", "toaster/metal.pkm").a("color_shift_map", "toaster/color_shift_map.png").a("overlay_map", "toaster/overlay_map.png").a("soft_light_map", "toaster/soft_light_map.png"));
    localObject1 = new b();
    a = 20;
    b = "Walden";
    c = t.filter_walden;
    d = "Walden";
    f = "shared/border_black.png";
    z = new a("WALDEN", 25, ((b)localObject1).a("map", "walden/map.png").a("vignette_map", "shared/vignette_map.png"));
    localObject1 = new b();
    a = 14;
    b = "1977";
    c = t.filter_1977;
    d = "Nineteen77";
    f = "shared/border_white.png";
    A = new a("NINETEEN77", 26, ((b)localObject1).a("map", "1977/map.png").a("screen_map", "1977/screen_map.png"));
    localObject1 = new b();
    a = 16;
    b = "Kelvin";
    c = t.filter_kelvin;
    d = "LordKelvin";
    f = "lord_kelvin/border.png";
    B = new a("KELVIN", 27, ((b)localObject1).a("map", "lord_kelvin/map.png"));
    localObject1 = new b();
    a = -2;
    b = "OES";
    d = "OES";
    C = new a("OES", 28, (b)localObject1);
    localObject1 = new b();
    a = -1;
    b = "YUV";
    d = "YUV";
    D = new a("YUV", 29, (b)localObject1);
    localObject1 = new b();
    a = 109;
    b = "Stinson";
    c = t.filter_stinson;
    d = "Stinson";
    E = new a("STINSON", 30, ((b)localObject1).a("map", "video/stinson/curves.png"));
    localObject1 = new b();
    a = 106;
    b = "Vesper";
    c = t.filter_vesper;
    d = "Vesper";
    F = new a("VESPER", 31, ((b)localObject1).a("map", "video/vesper/map.png"));
    localObject1 = new b();
    a = 112;
    b = "Clarendon";
    c = t.filter_clarendon;
    d = "Clarendon";
    G = new a("CLARENDON", 32, ((b)localObject1).a("map", "video/clarendon/Glacial1.png").a("map2", "video/clarendon/Glacial2.png"));
    localObject1 = new b();
    a = 118;
    b = "Maven";
    c = t.filter_maven;
    d = "Maven";
    H = new a("MAVEN", 33, ((b)localObject1).a("map1", "video/maven/Lansdowne1.png").a("map2", "video/maven/Lansdowne2.png"));
    localObject1 = new b();
    a = 114;
    b = "Gingham";
    c = t.filter_gingham;
    d = "Gingham";
    I = new a("GINGHAM", 34, ((b)localObject1).a("map", "video/gingham/curves1.png").a("mapLgg", "video/gingham/curves_lgg.png"));
    localObject1 = new b();
    a = 107;
    b = "Ginza";
    c = t.filter_ginza;
    d = "Ginza";
    J = new a("GINZA", 35, ((b)localObject1).a("map1", "video/ginza/curves1.png").a("map2", "video/ginza/curves2.png"));
    localObject1 = new b();
    a = 113;
    b = "Skyline";
    c = t.filter_skyline;
    d = "Skyline";
    K = new a("SKYLINE", 36, ((b)localObject1).a("map", "video/skyline/curves.png"));
    localObject1 = new b();
    a = 105;
    b = "Dogpatch";
    c = t.filter_dogpatch;
    d = "Dogpatch";
    L = new a("DOGPATCH", 37, ((b)localObject1).a("map1", "video/dogpatch/curves1.png").a("mapLgg", "video/dogpatch/curves_lgg.png"));
    localObject1 = new b();
    a = 115;
    b = "Brooklyn";
    c = t.filter_brooklyn;
    d = "Brooklyn";
    M = new a("BROOKLYN", 38, ((b)localObject1).a("map", "video/brooklyn/curves.png"));
    localObject1 = new b();
    a = 111;
    b = "Moon";
    c = t.filter_moon;
    d = "Moon";
    N = new a("MOON", 39, ((b)localObject1).a("map1", "video/moon/curves1.png").a("map2", "video/moon/curves2.png"));
    localObject1 = new b();
    a = 117;
    b = "Helena";
    c = t.filter_helena;
    d = "Helena";
    O = new a("HELENA", 40, ((b)localObject1).a("map1", "video/helena/epic_1.png").a("map2", "video/helena/epic_2.png"));
    localObject1 = new b();
    a = 116;
    b = "Ashby";
    c = t.filter_ashby;
    d = "Ashby";
    P = new a("ASHBY", 41, ((b)localObject1).a("tonemap", "video/ashby/tonemap.png").a("levels", "video/ashby/levels.png"));
    localObject1 = new b();
    a = 108;
    b = "Charmes";
    c = t.filter_charmes;
    d = "Charmes";
    Q = new a("CHARMES", 42, ((b)localObject1).a("map", "video/charmes/map.png"));
    Y = new a[] { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q };
    X = new SparseArray();
    localObject1 = values();
    int i2 = localObject1.length;
    while (i1 < i2)
    {
      Object localObject2 = localObject1[i1];
      X.put(R, localObject2);
      i1 += 1;
    }
  }
  
  private a(b paramb)
  {
    R = a;
    S = b;
    T = c;
    U = d;
    V = e;
    W = f;
  }
  
  public static a a(int paramInt)
  {
    return (a)X.get(paramInt);
  }
}

/* Location:
 * Qualified Name:     com.instagram.creation.a.a
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */