package com.instagram.d;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class g
{
  public static final m A;
  public static final k B;
  public static final k C;
  public static final k D;
  public static final k E;
  public static final j F;
  public static final k G;
  public static final m H;
  public static final m I;
  public static final m J;
  public static final m K;
  public static final m L;
  public static final m M;
  public static final m N;
  public static final m O;
  public static final m P;
  public static final m Q;
  public static final m R;
  public static final k S;
  public static final b T;
  public static final b U;
  public static final k V;
  public static final l W;
  public static final k X;
  public static final k Y;
  public static final b Z;
  public static final b a;
  public static final j aA;
  public static final j aB;
  public static final b aC;
  public static final j aD;
  public static final j aE;
  public static final j aF;
  public static final j aG;
  public static final b aH;
  public static final b aI;
  public static final b aJ;
  public static final k aK;
  public static final b aL;
  public static final k aM;
  public static final j aN;
  public static final m aO;
  public static final b aP;
  public static final j aQ;
  public static final c aR;
  public static final l aS;
  public static final j aT;
  public static final b aU;
  public static final b aV;
  public static final b aW;
  public static final b aX;
  public static final b aY;
  public static final b aZ;
  public static final b aa;
  public static final j ab;
  public static final b ac;
  public static final b ad;
  public static final c ae;
  public static final b af;
  public static final k ag;
  public static final m ah;
  public static final l ai;
  public static final k aj;
  public static final b ak;
  public static final k al;
  public static final k am;
  public static final k an;
  public static final b ao;
  public static final k ap;
  public static final k aq;
  public static final m ar;
  public static final k as;
  public static final k at;
  public static final k au;
  public static final j av;
  public static final j aw;
  public static final j ax;
  public static final j ay;
  public static final b az;
  public static final b b;
  public static final c bA;
  public static final b bB;
  public static final b bC;
  public static final b bD;
  public static final b bE;
  public static final c bF;
  public static final b bG;
  public static final b bH;
  public static final b bI;
  public static final b bJ;
  public static final b bK;
  public static final b bL;
  public static final b bM;
  public static final b bN;
  public static final b bO;
  public static final b bP;
  public static final b bQ;
  public static final j bR;
  public static final b bS;
  public static final b bT;
  public static final b bU;
  public static final b bV;
  public static final b bW;
  public static final b bX;
  public static final b bY;
  public static final b bZ;
  public static final b ba;
  public static final b bb;
  public static final j bc;
  public static final j bd;
  public static final j be;
  public static final b bf;
  public static final b bg;
  public static final b bh;
  public static final c bi;
  public static final b bj;
  public static final b bk;
  public static final b bl;
  public static final b bm;
  public static final b bn;
  public static final b bo;
  public static final c bp;
  public static final b bq;
  public static final j br;
  public static final b bs;
  public static final c bt;
  public static final j bu;
  public static final j bv;
  public static final b bw;
  public static final j bx;
  public static final c by;
  public static final j bz;
  public static final b c;
  public static final j cA;
  public static final b cB;
  public static final b cC;
  public static final b cD;
  public static final c cE;
  public static final b cF;
  public static final b cG;
  public static final b cH;
  public static final b cI;
  public static final b cJ;
  public static final b cK;
  public static final j cL;
  public static final j cM;
  public static final b cN;
  public static final c cO;
  public static final j cP;
  public static final j cQ;
  public static final j cR;
  public static final j cS;
  public static final j cT;
  public static final c cU;
  public static final j cV;
  public static final j cW;
  public static final j cX;
  public static final j cY;
  public static final j cZ;
  public static final b ca;
  public static final b cb;
  public static final b cc;
  public static final b cd;
  public static final b ce;
  public static final b cf;
  public static final c cg;
  public static final b ch;
  public static final j ci;
  public static final j cj;
  public static final j ck;
  public static final b cl;
  public static final j cm;
  public static final j cn;
  public static final j co;
  public static final j cp;
  public static final j cq;
  public static final j cr;
  public static final b cs;
  public static final j ct;
  public static final j cu;
  public static final j cv;
  public static final j cw;
  public static final b cx;
  public static final b cy;
  public static final b cz;
  public static final b d;
  public static final b dA;
  public static final b dB;
  public static final b dC;
  public static final j dD;
  public static final j dE;
  public static final j dF;
  public static final j dG;
  public static final j dH;
  public static final b dI;
  public static final List<c> dJ;
  private static final b dK;
  private static final b dL;
  private static final b dM;
  private static final b dN;
  private static final b dO;
  private static final b dP;
  private static final b dQ;
  private static final j dR;
  private static final b dS;
  private static final j dT;
  private static final j dU;
  private static final j dV;
  private static final j dW;
  private static final j dX;
  private static final j dY;
  private static final j dZ;
  public static final j da;
  public static final j db;
  public static final c dc;
  public static final c dd;
  public static final c de;
  public static final c df;
  public static final j dg;
  public static final b dh;
  public static final b di;
  public static final b dj;
  public static final b dk;
  public static final b dl;
  public static final b dm;
  public static final b dn;
  public static final b jdField_do;
  public static final b dp;
  public static final b dq;
  public static final k dr;
  public static final k ds;
  public static final k dt;
  public static final m du;
  public static final b dv;
  public static final k dw;
  public static final b dx;
  public static final b dy;
  public static final c dz;
  public static final b e;
  private static final b eA;
  private static final j ea;
  private static final j eb;
  private static final j ec;
  private static final j ed;
  private static final b ee;
  private static final b ef;
  private static final c eg;
  private static final b eh;
  private static final b ei;
  private static final b ej;
  private static final j ek;
  private static final c el;
  private static final b em;
  private static final b en;
  private static final b eo;
  private static final b ep;
  private static final b eq;
  private static final b er;
  private static final j es;
  private static final b et;
  private static final b eu;
  private static final b ev;
  private static final b ew;
  private static final b ex;
  private static final b ey;
  private static final j ez;
  public static final b f;
  public static final b g;
  public static final b h;
  public static final b i;
  public static final b j;
  public static final b k;
  public static final b l;
  public static final b m;
  public static final b n;
  public static final b o;
  public static final b p;
  public static final b q;
  public static final b r;
  public static final h s;
  public static final h t;
  public static final h u;
  public static final b v;
  public static final b w;
  public static final k x;
  public static final k y;
  public static final k z;
  
  static
  {
    Object localObject1 = new a("ig_android_contact_point_triage", d.m);
    c = "phone_first";
    d = e.b;
    a = ((a)localObject1).a();
    localObject1 = new a("ig_android_one_click_in_old_flow", d.m);
    c = "one_click_sms";
    d = e.b;
    b = ((a)localObject1).a();
    localObject1 = new a("ig_android_mandatory_full_name", "is_mandatory", d.m);
    d = e.b;
    c = ((a)localObject1).a();
    localObject1 = new a("ig_android_fb_nux_holdout", "skip_fb_friends", d.m);
    d = e.b;
    d = ((a)localObject1).a();
    localObject1 = new a("ig_android_non_fb_sso", "support_non_fb_sso", d.m);
    d = e.b;
    e = ((a)localObject1).a();
    localObject1 = new a("ig_android_use_email_as_username_suggestion", "use_email", d.m);
    d = e.b;
    f = ((a)localObject1).a();
    localObject1 = new a("ig_android_reg_phone_email_active_state", "phone_num_len_enable_next_button", d.m);
    d = e.b;
    g = ((a)localObject1).a();
    localObject1 = new a("ig_android_reg_phone_email_active_state", "valid_email_syntax", d.m);
    d = e.b;
    h = ((a)localObject1).a();
    localObject1 = new a("ig_android_reg_enable_login_password_btn", "login_password_len_valid", d.m);
    d = e.b;
    i = ((a)localObject1).a();
    localObject1 = new a("ig_android_reg_next_btn_active_state", "outline_opaque", d.m);
    d = e.b;
    j = ((a)localObject1).a();
    localObject1 = new a("ig_android_reg_next_btn_active_state", "button_filled", d.m);
    d = e.b;
    k = ((a)localObject1).a();
    localObject1 = new a("ig_android_reg_next_btn_active_state", "button_filled_fade_in", d.m);
    d = e.b;
    l = ((a)localObject1).a();
    localObject1 = new a("ig_android_reg_login_btn_active_state", "outline_opaque", d.m);
    d = e.b;
    m = ((a)localObject1).a();
    localObject1 = new a("ig_android_reg_login_btn_active_state", "button_filled", d.m);
    d = e.b;
    n = ((a)localObject1).a();
    localObject1 = new a("ig_android_reg_login_btn_active_state", "button_filled_fade_in", d.m);
    d = e.b;
    o = ((a)localObject1).a();
    localObject1 = new a("ig_android_reg_sticky_errors", "sticky_errors", d.m);
    d = e.b;
    p = ((a)localObject1).a();
    localObject1 = new a("ig_android_show_fb_social_context_in_nux", "show_context", d.m);
    d = e.b;
    q = ((a)localObject1).a();
    localObject1 = new a("ig_android_upsell_login_as_handle", "do_upsell", d.m);
    d = e.b;
    r = ((a)localObject1).a();
    s = new h("ig_creation_growth_holdout");
    t = new h("ig_android_ads_holdout_universe");
    u = new h("ig_timestamp_public_test");
    v = b.a("ig_android_ads_heatmap_overlay_universe", d.a);
    localObject1 = new a("ig_android_ads_cta_universe", d.a);
    c = "overlay_on_like";
    dK = ((a)localObject1).a();
    localObject1 = new a("ig_android_ads_cta_universe", d.a);
    c = "cta_in_profile";
    dL = ((a)localObject1).a();
    localObject1 = new a("ig_android_ads_full_width_cta_universe", d.a);
    c = "full_width";
    dM = ((a)localObject1).a();
    localObject1 = new a("ig_android_ads_full_width_cta_universe", d.a);
    c = "move_indicator";
    dN = ((a)localObject1).a();
    localObject1 = new a("ig_android_ads_full_width_cta_universe", d.a);
    c = "enable_overlay";
    dO = ((a)localObject1).a();
    dP = b.a("ig_android_ads_loop_count_universe", d.a);
    dQ = b.a("ig_android_ads_indicator_change_universe", d.a);
    localObject1 = new i("ig_android_ads_overlay_design_universe", "design", d.a);
    e = 0;
    dR = ((i)localObject1).a();
    dS = new a("ig_android_ads_heatmap_click_detect_universe", "is_enabled", d.a).a();
    localObject1 = new i("ig_android_ads_heatmap_click_detect_universe", "media_left", d.a);
    e = 0;
    dT = ((i)localObject1).a();
    localObject1 = new i("ig_android_ads_heatmap_click_detect_universe", "media_right", d.a);
    e = 0;
    dU = ((i)localObject1).a();
    localObject1 = new i("ig_android_ads_heatmap_click_detect_universe", "media_top", d.a);
    e = 0;
    dV = ((i)localObject1).a();
    localObject1 = new i("ig_android_ads_heatmap_click_detect_universe", "media_bottom", d.a);
    e = 0;
    dW = ((i)localObject1).a();
    localObject1 = new i("ig_android_ads_heatmap_click_detect_universe", "cta_left", d.a);
    e = 0;
    dX = ((i)localObject1).a();
    localObject1 = new i("ig_android_ads_heatmap_click_detect_universe", "cta_right", d.a);
    e = 0;
    dY = ((i)localObject1).a();
    localObject1 = new i("ig_android_ads_heatmap_click_detect_universe", "cta_top", d.a);
    e = 0;
    dZ = ((i)localObject1).a();
    localObject1 = new i("ig_android_ads_heatmap_click_detect_universe", "cta_bottom", d.a);
    e = 0;
    ea = ((i)localObject1).a();
    localObject1 = new i("ig_android_ads_heatmap_click_detect_universe", "fling_speed", d.a);
    e = 0;
    eb = ((i)localObject1).a();
    localObject1 = new i("ig_android_ads_heatmap_click_detect_universe", "media_vp", d.a);
    e = 0;
    ec = ((i)localObject1).a();
    localObject1 = new i("ig_android_ads_heatmap_click_detect_universe", "cta_vp", d.a);
    e = 0;
    ed = ((i)localObject1).a();
    w = new a("ig_android_pbia_normal_weight_universe", "is_enabled", d.a).a();
    x = new k(t, dK);
    y = new k(t, dP);
    z = new k(t, dQ);
    A = new m(t, dR);
    B = new k(t, dL);
    C = new k(t, dM);
    D = new k(t, dN);
    E = new k(t, dO);
    F = new i("ig_android_ads_cta_in_profile_style_universe", "style", d.a).a();
    G = new k(t, dS);
    H = new m(t, dT);
    I = new m(t, dU);
    J = new m(t, dV);
    K = new m(t, dW);
    L = new m(t, dX);
    M = new m(t, dY);
    N = new m(t, dZ);
    O = new m(t, ea);
    P = new m(t, eb);
    Q = new m(t, ec);
    R = new m(t, ed);
    ee = new a("ig_android_pending_edits_dialog_universe", "alert_if_filtered_or_visited_share_screen", d.c).a();
    S = new k(s, ee);
    T = new a("ig_android_comment_retry_tweaks_universe", "hide_dialog", d.c).a();
    U = new a("ig_android_comment_retry_tweaks_universe", "show_retry_button", d.c).a();
    ef = new a("ig_android_drafts_universe", "android_drafts_enabled", d.c).a();
    V = new k(s, ef);
    eg = new c("ig_android_drafts_universe", "android_entry_point", "none", d.c, new String[] { "none", "profile", "inline_gallery" });
    W = new l(s, eg);
    eh = new a("ig_android_video_default_trim", "is_enabled", d.c).a();
    X = new k(s, eh);
    ei = new a("ig_android_direct_post_to_feed", "is_enabled", d.c).a();
    Y = new k(s, ei);
    Z = b.a("ig_android_swipeable_filters_blacklist", d.d);
    aa = b.a("ig_android_add_to_last_post", d.d);
    ab = new j("ig_android_add_to_last_post", "album_paging_timeout_ms", 4000, d.d);
    ac = b.a("ig_android_boomerang_entry", d.d);
    ad = b.a("ig_android_boomerang_feed_attribution", d.d);
    ae = new c("ig_android_post_auto_retry_v7_21", "auto_retry_mode", "default", d.d, new String[] { "default", "never", "auto", "manual", "last" });
    localObject1 = new a("ig_android_post_auto_retry_v7_21", d.d);
    c = "auto_retry_fast";
    af = ((a)localObject1).a();
    localObject1 = new a("ig_android_grid_video_icon", d.d);
    c = "android_new_icon_enabled";
    ej = ((a)localObject1).a();
    ag = new k(s, ej);
    ek = new j("ig_android_grid_video_icon", "android_icon_opacity", 100, d.d);
    ah = new m(s, ek);
    el = new c("ig_android_grid_video_icon", "android_icon_position", "top_right", d.d, new String[] { "bottom_left", "top_right" });
    ai = new l(s, el);
    localObject1 = new a("ig_android_last_edits", d.d);
    c = "droid_last_edits_enabled";
    em = ((a)localObject1).a();
    aj = new k(s, em);
    localObject1 = new a("ig_peek_profile_photo_universe", d.d);
    c = "peek_profile_photo_enabled";
    ak = ((a)localObject1).a();
    en = new a("ig_android_video_capture_experiment", "android_video_capture_timer_enabled", d.d).a();
    al = new k(s, en);
    eo = new a("ig_android_video_capture_experiment", "android_video_clip_bar_enabled", d.d).a();
    am = new k(s, eo);
    ep = new a("ig_android_two_step_capture_flow", "android_two_step_capture_flow_enabled", d.d).a();
    an = new k(s, ep);
    ao = b.a("ig_android_event_creation", "is_showing_event_icon", d.d);
    localObject1 = new a("ig_android_inline_gallery_universe", d.i);
    c = "ig_android_inline_gallery_enabled";
    eq = ((a)localObject1).a();
    ap = new k(s, eq);
    localObject1 = new a("ig_android_inline_gallery_no_backoff_on_launch_universe", d.i);
    c = "ig_android_inline_gallery_no_backoff_on_launch";
    er = ((a)localObject1).a();
    aq = new k(s, er);
    es = new j("ig_android_inline_gallery_backoff_hours_universe", "ig_android_inline_gallery_backoff_hours", 24, d.i);
    ar = new m(s, es);
    et = b.a("ig_android_animate_share_button", "animate_bounce_enabled", d.d);
    as = new k(s, et);
    eu = b.a("ig_android_animate_share_button", "animate_shimmer_enabled", d.d);
    at = new k(s, eu);
    ev = b.a("ig_android_direct_blue_tab", "blue_direct_button_enabled", d.c);
    au = new k(s, ev);
    av = new j("ig_android_rendering_controls", "render_tile_size_light_filters", 540, d.q);
    aw = new j("ig_android_rendering_controls", "render_tile_size_heavy_filters", 270, d.q);
    ax = new j("ig_android_rendering_controls", "min_high_res_upload_width", 320, d.q);
    ay = new j("ig_android_rendering_controls", "max_high_res_upload_width", 1080, d.q);
    localObject1 = new a("ig_android_rendering_controls", d.q);
    c = "high_quality_downsample_enabled";
    d = e.a;
    e = true;
    az = ((a)localObject1).a();
    aA = new j("ig_android_rendering_controls", "min_width_for_video_high_quality_downsample", 1280, d.q);
    aB = new j("ig_android_histogram_reporter", "report_rate", 0, d.q);
    aC = b.a("ig_android_disable_chroma_subsampling", d.k);
    aD = new j("ig_android_high_res_upload_2", "quality_small", 95, d.k);
    aE = new j("ig_android_high_res_upload_2", "size_small", 200, d.k);
    aF = new j("ig_android_high_res_upload_2", "quality_large", 70, d.k);
    aG = new j("ig_android_high_res_upload_2", "size_large", 1080, d.k);
    aH = b.a("ig_android_progressive_jpeg", "corner_indicator", d.h);
    aI = b.a("ig_android_share_spinner", d.h);
    aJ = b.a("ig_android_feed_pill", d.h);
    aK = new k(u, aJ);
    aL = b.a("ig_android_media_tighten_space", d.h);
    aM = new k(u, aL);
    aN = new j("ig_android_media_tighten_space", "line_height", 0, d.h);
    aO = new m(u, aN);
    aP = b.a("ig_android_progressive_jpeg", "feed", d.h);
    aQ = new j("ig_android_progressive_jpeg", "min_scan", Integer.MAX_VALUE, d.h);
    aR = new c("ig_android_feed_ufi_redesign", "experiment_flavor", "ufi", d.h, new String[] { "ufi", "ufi_with_count", "ufi_with_text" });
    aS = new l(u, aR);
    aT = new j("ig_android_app_start_config", "app_start_max_elapsed_ms", 10000, d.h);
    aU = b.a("is_android_feed_seen_state", "is_enabled", d.h);
    aV = b.a("ig_android_following_tab", "enable_contextual_feed", d.n);
    aW = b.a("ig_android_direct_emoji_picker", d.e);
    aX = b.a("ig_android_direct_plus_button", d.e);
    localObject1 = new a("ig_android_direct_drawing_in_quick_cam_universe", d.e);
    c = "ig_android_enable_drawing_in_direct_quick_cam";
    aY = ((a)localObject1).a();
    aZ = b.a("ig_android_dv2_realtime_private_share", d.e);
    ba = b.a("ig_android_direct_mutually_exclusive_experiment_universe", "use_sqlite", d.e);
    bb = b.a("ig_android_feed_reshare_button_nux", d.e);
    bc = new j("ig_android_feed_reshare_button_nux", "maximum_nux_quota", 3, d.e);
    bd = new j("ig_android_feed_reshare_button_nux", "minimum_nux_reshow_interval_seconds", 43200, d.e);
    be = new j("ig_android_feed_reshare_button_nux", "interval_for_nux_reactivation_after_reshare_action_seconds", -1, d.e);
    bf = b.a("ig_android_mini_inbox_2", "enable_actionbar_pinning", d.e);
    bg = b.a("ig_android_direct_mutually_exclusive_experiment_universe", "use_new_thread_ui", d.e);
    bh = b.a("ig_android_direct_mutually_exclusive_experiment_universe", "is_variable_sized_media", d.e);
    bi = new c("ig_android_direct_mutually_exclusive_experiment_universe", "percentage_width", "0", d.e);
    bj = b.a("ig_android_direct_glyph", "is_enabled", d.e);
    bk = b.a("ig_android_direct_send_auto_retry_universe", "enable_auto_retry", d.e);
    bl = b.a("ig_android_mentions_dismiss_rule", "is_enabled", d.e);
    bm = b.a("ig_android_direct_ranked_contacts", "is_enabled", d.e);
    bn = b.a("ig_android_channels_home", "enable_channels_home", d.f);
    bo = b.a("ig_android_immersive_viewer", "enable_feed_header", d.f);
    bp = new c("ig_android_prefetch_explore", "experiment_flavor", "no_prefetch_explore", d.f, new String[] { "no_prefetch_explore", "prefetch_explore", "prefetch_explore_in_wifi", "prefetch_explore_with_delay" });
    bq = b.a("ig_explore_v3_android_universe", "auto_refresh_enabled", d.f);
    localObject1 = new i("ig_explore_v3_android_universe", "auto_refresh_impression_threshold", d.f);
    e = 2;
    br = ((i)localObject1).a();
    bs = b.a("ig_android_progressive_jpeg", "grid", d.f);
    bt = new c("ig_android_immersive_viewer", "feed_entry_type", "immersive_viewer", d.f, new String[] { "immersive_viewer", "contextual_hide_comments", "contextual_with_comments" });
    bu = new j("ig_android_immersive_viewer", "swipe_threshold", 0, d.f);
    localObject1 = new i("ig_android_image_cache_multi_queue", "preview_blur_radius", d.f);
    e = 3;
    bv = ((i)localObject1).a();
    bw = b.a("ig_android_infinite_scrolling", d.r);
    bx = new j("ig_android_infinite_scrolling", "num_results", 10, d.r);
    by = new c("ig_android_search_null_state", "experiment_flavor", "search_null_state_with_hide_item", d.r, new String[] { "search_hide_item", "search_null_state_with_hide_item" });
    bz = new j("ig_android_search_null_state", "number_of_search_history_item", 1, d.r);
    bA = new c("ig_android_search_client_matching", "experiment_flavor", "autocomplete_matching", d.r, new String[] { "autocomplete_matching", "autocomplete_and_client_side_matching" });
    localObject1 = new a("ig_android_follow_search_bar", d.r);
    c = "following_enabled";
    bB = ((a)localObject1).a();
    localObject1 = new a("ig_android_follow_search_bar", d.r);
    c = "follower_enabled";
    bC = ((a)localObject1).a();
    bD = b.a("ig_android_pending_request_search_bar", d.r);
    localObject1 = new a("ig_ranking_following", d.r);
    c = "enable_social_context";
    bE = ((a)localObject1).a();
    bF = new c("ig_android_following_follower_social_context", "experiment_flavor", "control", d.r, new String[] { "control", "small_follow_button", "replace_full_name" });
    bG = b.a("ig_android_search", "disable_queued_requests", d.r);
    bH = b.a("ig_android_search", "show_seen_dot", d.r);
    bI = b.a("ig_android_enable_share_to_messenger", d.j);
    bJ = b.a("ig_android_enable_share_to_whatsapp", d.j);
    bK = b.a("ig_android_options_app_invite", d.j);
    bL = b.a("ig_android_full_people_card_in_user_list", d.j);
    bM = b.a("ig_android_media_favorites", d.j);
    bN = b.a("ig_android_2fac", d.j);
    bO = b.a("ig_android_bigger_share_button", d.j);
    bP = b.a("ig_android_feed_unit_hscroll_auto_advance", "auto_advance", d.j);
    bQ = b.a("ig_android_feed_unit_footer", "feed_unit_footer", d.j);
    bR = new j("ig_android_private_follow_request", "max_number_of_row", 2, d.j);
    bS = b.a("ig_android_nux_holdout", "skip_ci_friends", d.j);
    bT = b.a("ig_android_nux_holdout", "skip_follow_more_people", d.j);
    bU = b.a("ig_android_explore_people_feed_icon", "show_icon", d.j);
    bV = b.a("ig_android_non_square_first", "is_non_square", d.j);
    bW = b.a("ig_android_profile", "follow_button_in_single_media", d.j);
    bX = b.a("ig_android_action_bar_text_button", "use_text", d.j);
    bY = b.a("ig_android_newsfeed_you_sections", "people_activity_sections", d.j);
    bZ = b.a("ig_android_discover_people_compact", "show_compact_row", d.j);
    ca = b.a("ig_android_recommended_user_compact", "show_compact_row", d.j);
    cb = b.a("ig_android_ru_page_update", "button_at_bottom", d.j);
    cc = b.a("ig_android_ru_page_update", "done_button_text_upper_right", d.j);
    cd = b.a("ig_android_invite_entry_point_universe", "use_blue_button", d.j);
    ce = b.a("ig_android_invite_entry_point_universe", "show_badge_count", d.j);
    localObject1 = new a("ig_fbns_blocked", d.g);
    d = e.c;
    cf = ((a)localObject1).a();
    cg = new c("ig_fbns_blocked", "config_url", "", d.g, e.c);
    localObject1 = new a("ig_fbns_push", d.g);
    d = e.c;
    ch = ((a)localObject1).a();
    ci = new j("ig_fbns_shared", "enable_shared_process", -1, d.g);
    cj = new j("ig_android_http_stack_experiment_2016", "stack_index", 2, d.l);
    ck = new j("ig_android_http_stack_experiment_2016", "sampling", 10000, d.l);
    cl = b.a("ig_android_http_stack_experiment_2016", "per_domain_limit", d.l);
    cm = new j("ig_android_http_stack_experiment_2016", "http_sessions", 6, d.l);
    cn = new j("ig_android_http_stack_experiment_2016", "http2_sessions", 2, d.l);
    co = new j("ig_android_http_stack_experiment_2016", "retry_limit", 1, d.l);
    cp = new j("ig_android_http_stack_experiment_2016", "priority_adjustment", 0, d.l);
    cq = new j("liger_instagram_android_univ", "stack", 0, d.l);
    cr = new j("liger_instagram_android_univ", "sampling", 10000, d.l);
    cs = b.a("liger_instagram_android_univ", "per_domain_limit", d.l);
    ct = new j("liger_instagram_android_univ", "http_sessions", 6, d.l);
    cu = new j("liger_instagram_android_univ", "http2_sessions", 2, d.l);
    cv = new j("liger_instagram_android_univ", "retry_limit", 1, d.l);
    cw = new j("liger_instagram_android_univ", "priority_adjustment", 0, d.l);
    cx = b.a("ig_android_react_native_notification_setting", d.l);
    cy = b.a("ig_android_react_native_edit_profile", "ig_android_react_native_edit_profile_enabled", d.l);
    cz = b.a("ig_android_anrwatchdog", d.l);
    cA = new j("ig_android_network_cancellation", "search_keep_alive_counts", -1, d.l);
    cB = b.a("ig_android_fix_ise_two_phase", d.l);
    cC = b.a("ig_android_disk_usage", "is_enabled", d.l);
    cD = b.a("ig_android_os_version_blocking", "is_enabled", d.l);
    cE = new c("ig_android_os_version_blocking", "redirect_url", "https://www.instagram.com", d.l);
    localObject1 = new a("ig_android_video_stitching_7_23", d.s);
    c = "stitching_all";
    cF = ((a)localObject1).a();
    cG = b.a("ig_android_video_download_logging", d.s);
    cH = b.a("ig_android_view_count_decouple_likes_universe", d.s);
    cI = b.a("ig_android_exoplayer", "is_enabled", d.s);
    cJ = b.a("ig_android_exoplayer", "is_remote", d.s);
    cK = b.a("ig_android_video_reuse_surface", "is_enabled", d.s);
    cL = new j("ig_android_video_cache_policy", "size_ratio_percent", 100, d.s);
    cM = new j("ig_android_video_playback_bandwidth_threshold", "size_ratio_percent", 0, d.s);
    cN = b.a("ig_android_video_loopcount_int", "is_enabled", d.s);
    cO = new c("ig_android_video_captions_universe", "mode", "control", d.s, new String[] { "control", "always", "only_muted" });
    cP = new j("ig_android_universe_video_production", "upload_width_min", 480, d.s);
    cQ = new j("ig_android_universe_video_production", "upload_width_max_low", 540, d.s);
    cR = new j("ig_android_universe_video_production", "upload_width_max_mid", 640, d.s);
    cS = new j("ig_android_universe_video_production", "upload_width_max_high", 720, d.s);
    cT = new j("ig_android_universe_video_production", "upload_width_max_hi_res_landscape", 720, d.s);
    cU = new c("ig_android_universe_video_production", "aspect_threshold_for_hi_res_landscape", "100000.0", d.s);
    cV = new j("ig_android_universe_video_production", "cpu_cores_low", 1, d.s);
    cW = new j("ig_android_universe_video_production", "cpu_cores_mid", 1, d.s);
    cX = new j("ig_android_universe_video_production", "total_memory_low", 520, d.s);
    cY = new j("ig_android_universe_video_production", "total_memory_mid", 1000, d.s);
    cZ = new j("ig_android_universe_video_production", "screen_width_low", 500, d.s);
    da = new j("ig_android_universe_video_production", "screen_width_mid", 700, d.s);
    db = new j("ig_android_universe_video_production", "configure_timeout_max_retry", 5, d.s);
    dc = new c("ig_android_universe_video_production", "upload_per_pixel_bit_rate_square", "7.0", d.s);
    dd = new c("ig_android_universe_video_production", "upload_per_pixel_bit_rate_16by9", "9.7222", d.s);
    de = new c("ig_android_universe_video_production", "upload_per_pixel_bit_rate_9by16", "7.0", d.s);
    df = new c("ig_android_universe_video_production", "upload_bit_rate_multiplier_for_fast_videos", "1.3", d.s);
    dg = new j("ig_video_max_duration_qe_preuniverse", "max_duration_sec", 60, d.s);
    dh = b.a("ig_video_use_sve_universe", d.s);
    di = b.a("ig_android_video_interleaved_v2", d.s);
    dj = b.a("ig_video_copyright_whitelist", d.s);
    dk = b.a("ig_android_profile", "contextual_feed_enabled", d.p);
    dl = b.a("ig_android_profile", "action_bar_persistent", d.p);
    dm = b.a("ig_android_profile", "action_bar_follow_button", d.p);
    dn = b.a("ig_android_profile", "hide_profile_list_enabled", d.p);
    do = b.a("ig_android_profile_link_iab", "is_enabled", d.p);
    dp = b.a("ig_android_profile", "truncated_bio_is_enabled", d.p);
    dq = b.a("ig_android_profile", "hide_profile_maps_enabled", d.p);
    ew = b.a("ig_android_share_profile_photo", "is_enabled", d.p);
    dr = new k(s, ew);
    ex = b.a("ig_android_share_profile_photo", "download_and_share_is_enabled", d.p);
    ds = new k(s, ex);
    ey = b.a("ig_android_share_profile_photo", "skip_share_screen_enabled", d.p);
    dt = new k(s, ey);
    localObject1 = new i("ig_android_facebook_twitter_profile_photos", "experiment_type", d.p);
    e = 0;
    ez = ((i)localObject1).a();
    du = new m(s, ez);
    dv = b.a("ig_android_user_detail_endpoint", "enable_username_endpoint", d.p);
    eA = new a("ig_android_share_profile_photo", "blue_prompt_button_enabled", d.p).a();
    dw = new k(s, eA);
    dx = b.a("ig_android_business_django_endpoint", "is_enabled", d.b);
    dy = b.a("ig_android_business_promotion", "is_enabled", d.b);
    dz = new c("ig_android_contact_button_redesign", "design_flavor", "control", d.b, new String[] { "control", "narrower_contact_button", "fluctuating_contact_button", "contact_in_bio", "wide_contact_button" });
    dA = b.a("ig_android_profanity_filter", d.o);
    dB = b.a("ig_android_periodic_analytics_upload_v2", d.o);
    dC = b.a("ig_android_blocked_list", "show_list", d.o);
    dD = new j("ig_android_periodic_analytics_upload_v2", "upload_interval_seconds", 120, d.o);
    localObject1 = new i("ig_android_analytics_data_loss", "max_batches_to_keep", d.o);
    e = 500;
    d = e.b;
    dE = ((i)localObject1).a();
    localObject1 = new i("ig_android_analytics_data_loss", "store_batch_delay_time", d.o);
    e = 15;
    d = e.b;
    dF = ((i)localObject1).a();
    localObject1 = new i("ig_android_phoneid_sync_interval", "fully_synced", d.o);
    e = 604800;
    d = e.b;
    dG = ((i)localObject1).a();
    localObject1 = new i("ig_android_phoneid_sync_interval", "partially_synced", d.o);
    e = 86400;
    d = e.b;
    dH = ((i)localObject1).a();
    dI = b.a("ig_android_iab_separate_dir", "is_enalbed", d.o);
    localObject1 = new ArrayList();
    Field[] arrayOfField = g.class.getDeclaredFields();
    int i2 = arrayOfField.length;
    int i1 = 0;
    for (;;)
    {
      Object localObject2;
      if (i1 < i2) {
        localObject2 = arrayOfField[i1];
      }
      try
      {
        localObject2 = ((Field)localObject2).get(null);
        if ((localObject2 instanceof c)) {
          ((List)localObject1).add((c)localObject2);
        }
        i1 += 1;
        continue;
        dJ = Collections.unmodifiableList((List)localObject1);
        return;
      }
      catch (IllegalAccessException localIllegalAccessException)
      {
        for (;;) {}
      }
    }
  }
}

/* Location:
 * Qualified Name:     com.instagram.d.g
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */